### ISSUE TITLE
MFManagedEncode

### ISSUE THREAD

**Issue by wimh** [roman380/msdnblogsmfsamples#1]
Seems to be available at https://sourceforge.net/p/mfnet/discussion/711229/thread/1dea870a/, but I did not check whether it is complete and unmodified.

Also, there is a MFSimpleEncode.zip on s.pudn.com/upload_log_en.asp?e=3657837 (be careful with the spam links), but it requires an account to be able to download it. The file listing seems to match though.

**Comment by roman380** [comment]
Thanks, I added it. I did see MFSimpleEncode there and it also looks good but I was unable to register neither via English nor via Chinese version of the site. So let's see if someone has it on hands to share.
