### ISSUE TITLE
Would be great to have a linux version 

### ISSUE THREAD

**Issue by danFromTelAviv** [roman380/msdnblogsmfsamples#3]
This seems to be the only way to convert media files into wmv3 on the web other than some ffmpeg patches. If you could create a make file for your code that would be really really awesome for lots of linux users  ( which is like all of the servers in the world ). 
Thanks,
Dan

**Comment by roman380** [comment]
This is sample code complementing Microsoft API on Windows. How do you think it is going to help you on Linux?

OK, I see your another question [How to convert a video to wmv3 format on linux](https://stackoverflow.com/questions/58689426/how-to-convert-a-video-to-wmv3-format-on-linux). No you can't run code from this repository on Linux. Just Windows.
